-- MySQL Script generated by MySQL Workbench
-- Tue Nov 26 14:08:25 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Location` (
  `Nome` VARCHAR(45) NOT NULL,
  `Nazione` VARCHAR(45) NOT NULL,
  `Città` VARCHAR(45) NOT NULL,
  `Capienza` INT NOT NULL,
  `Via` VARCHAR(45) NOT NULL,
  `N. civico` INT NOT NULL,
  PRIMARY KEY (`Nome`, `Nazione`, `Città`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Eventi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Eventi` (
  `IDevento` VARCHAR(10) NOT NULL,
  `Data_e_ora` DATETIME NOT NULL,
  `Nome_Location` VARCHAR(45) NOT NULL,
  `Città_Location` VARCHAR(45) NOT NULL,
  `Nazione_Location` VARCHAR(45) NOT NULL,
  `Biglietti disponibili` INT NOT NULL,
  `Categoria` VARCHAR(15) NOT NULL,
  `Nome_evento` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`IDevento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Biglietti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Biglietti` (
  `IDbiglietto` INT NOT NULL,
  `IDevento` VARCHAR(10) NOT NULL,
  `Posto` INT NOT NULL,
  `Username_Utente` VARCHAR(15) NULL,
  PRIMARY KEY (`IDbiglietto`, `IDevento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Utenti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Utenti` (
  `Username` VARCHAR(15) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Cognome` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Organizzatore` BINARY(2) NOT NULL,
  PRIMARY KEY (`Username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categorie` (
  `Nome` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Nome`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
