-- MySQL Script generated by MySQL Workbench
-- Thu Nov 28 16:51:03 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema eventBook
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eventBook
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eventBook` DEFAULT CHARACTER SET utf8 ;
USE `eventBook` ;

-- -----------------------------------------------------
-- Table `eventBook`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventBook`.`Location` (
  `Nome` VARCHAR(45) NOT NULL,
  `Nazione` VARCHAR(45) NOT NULL,
  `Città` VARCHAR(45) NOT NULL,
  `Capienza` INT NOT NULL,
  `Via` VARCHAR(45) NOT NULL,
  `N_civico` INT NOT NULL,
  PRIMARY KEY (`Nome`, `Nazione`, `Città`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventBook`.`Eventi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventBook`.`Eventi` (
  `IDevento` VARCHAR(10) NOT NULL,
  `Data_e_ora` DATETIME NOT NULL,
  `Nome_Location` VARCHAR(45) NOT NULL,
  `Città_Location` VARCHAR(45) NOT NULL,
  `Nazione_Location` VARCHAR(45) NOT NULL,
  `Biglietti_disponibili` INT NOT NULL,
  `Categoria` VARCHAR(15) NOT NULL,
  `Nome_evento` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`IDevento`),
  INDEX `Nome_location_idx` (`Nome_Location` ASC) VISIBLE,
  INDEX `Città_location_idx` (`Città_Location` ASC) VISIBLE,
  INDEX `Nazione_location_idx` (`Nazione_Location` ASC) VISIBLE,
  CONSTRAINT `Nome_location`
    FOREIGN KEY (`Nome_Location`)
    REFERENCES `eventBook`.`Location` (`Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Città_location`
    FOREIGN KEY (`Città_Location`)
    REFERENCES `eventBook`.`Location` (`Città`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Nazione_location`
    FOREIGN KEY (`Nazione_Location`)
    REFERENCES `eventBook`.`Location` (`Nazione`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventBook`.`Biglietti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventBook`.`Biglietti` (
  `IDbiglietto` INT NOT NULL,
  `IDevento` VARCHAR(10) NOT NULL,
  `Posto` INT NOT NULL,
  `Username_Utente` VARCHAR(15) NULL,
  PRIMARY KEY (`IDbiglietto`),
  INDEX `IDevento_idx` (`IDevento` ASC) VISIBLE,
  CONSTRAINT `IDevento`
    FOREIGN KEY (`IDevento`)
    REFERENCES `eventBook`.`Eventi` (`IDevento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventBook`.`Utenti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventBook`.`Utenti` (
  `Username` VARCHAR(15) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Cognome` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Organizzatore` BINARY(2) NOT NULL,
  PRIMARY KEY (`Username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventBook`.`Categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventBook`.`Categorie` (
  `Nome` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Nome`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
